/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegistoRouteImport } from './routes/registo'
import { Route as LoginRouteImport } from './routes/login'
import { Route as EmpresasRouteImport } from './routes/empresas'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as VerificarCodeRouteImport } from './routes/verificar.$code'
import { Route as DashboardWhatsappRouteImport } from './routes/dashboard.whatsapp'
import { Route as DashboardServicosRouteImport } from './routes/dashboard.servicos'
import { Route as DashboardRecibosRouteImport } from './routes/dashboard.recibos'
import { Route as DashboardProdutosRouteImport } from './routes/dashboard.produtos'
import { Route as DashboardPerfilRouteImport } from './routes/dashboard.perfil'
import { Route as DashboardNotificacoesRouteImport } from './routes/dashboard.notificacoes'
import { Route as DashboardFacturasRouteImport } from './routes/dashboard.facturas'
import { Route as DashboardFacturacaoRouteImport } from './routes/dashboard.facturacao'
import { Route as DashboardEquipaRouteImport } from './routes/dashboard.equipa'
import { Route as DashboardDocumentosRouteImport } from './routes/dashboard.documentos'
import { Route as DashboardDesignRouteImport } from './routes/dashboard.design'
import { Route as DashboardDefinicoesRouteImport } from './routes/dashboard.definicoes'
import { Route as DashboardCotacoesRouteImport } from './routes/dashboard.cotacoes'
import { Route as DashboardClientesRouteImport } from './routes/dashboard.clientes'
import { Route as DashboardAssistenteRouteImport } from './routes/dashboard.assistente'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as DashboardFacturasIndexRouteImport } from './routes/dashboard.facturas.index'
import { Route as DashboardEquipaIndexRouteImport } from './routes/dashboard.equipa.index'
import { Route as DashboardDocumentosIndexRouteImport } from './routes/dashboard.documentos.index'
import { Route as DashboardAssistenteIndexRouteImport } from './routes/dashboard.assistente.index'
import { Route as FacturasIdImprimirRouteImport } from './routes/facturas.$id.imprimir'
import { Route as DashboardFacturasNovaRouteImport } from './routes/dashboard.facturas.nova'
import { Route as DashboardFacturasIdRouteImport } from './routes/dashboard.facturas.$id'
import { Route as DashboardEquipaChannelIdRouteImport } from './routes/dashboard.equipa.$channelId'
import { Route as DashboardDocumentosNovoRouteImport } from './routes/dashboard.documentos.novo'
import { Route as DashboardAssistenteThreadIdRouteImport } from './routes/dashboard.assistente.$threadId'

const RegistoRoute = RegistoRouteImport.update({
  id: '/registo',
  path: '/registo',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const EmpresasRoute = EmpresasRouteImport.update({
  id: '/empresas',
  path: '/empresas',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const VerificarCodeRoute = VerificarCodeRouteImport.update({
  id: '/verificar/$code',
  path: '/verificar/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardWhatsappRoute = DashboardWhatsappRouteImport.update({
  id: '/whatsapp',
  path: '/whatsapp',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardServicosRoute = DashboardServicosRouteImport.update({
  id: '/servicos',
  path: '/servicos',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardRecibosRoute = DashboardRecibosRouteImport.update({
  id: '/recibos',
  path: '/recibos',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProdutosRoute = DashboardProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPerfilRoute = DashboardPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardNotificacoesRoute = DashboardNotificacoesRouteImport.update({
  id: '/notificacoes',
  path: '/notificacoes',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardFacturasRoute = DashboardFacturasRouteImport.update({
  id: '/facturas',
  path: '/facturas',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardFacturacaoRoute = DashboardFacturacaoRouteImport.update({
  id: '/facturacao',
  path: '/facturacao',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardEquipaRoute = DashboardEquipaRouteImport.update({
  id: '/equipa',
  path: '/equipa',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDocumentosRoute = DashboardDocumentosRouteImport.update({
  id: '/documentos',
  path: '/documentos',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDesignRoute = DashboardDesignRouteImport.update({
  id: '/design',
  path: '/design',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDefinicoesRoute = DashboardDefinicoesRouteImport.update({
  id: '/definicoes',
  path: '/definicoes',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCotacoesRoute = DashboardCotacoesRouteImport.update({
  id: '/cotacoes',
  path: '/cotacoes',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardClientesRoute = DashboardClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAssistenteRoute = DashboardAssistenteRouteImport.update({
  id: '/assistente',
  path: '/assistente',
  getParentRoute: () => DashboardRoute,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardFacturasIndexRoute = DashboardFacturasIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardFacturasRoute,
} as any)
const DashboardEquipaIndexRoute = DashboardEquipaIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardEquipaRoute,
} as any)
const DashboardDocumentosIndexRoute =
  DashboardDocumentosIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardDocumentosRoute,
  } as any)
const DashboardAssistenteIndexRoute =
  DashboardAssistenteIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardAssistenteRoute,
  } as any)
const FacturasIdImprimirRoute = FacturasIdImprimirRouteImport.update({
  id: '/facturas/$id/imprimir',
  path: '/facturas/$id/imprimir',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardFacturasNovaRoute = DashboardFacturasNovaRouteImport.update({
  id: '/nova',
  path: '/nova',
  getParentRoute: () => DashboardFacturasRoute,
} as any)
const DashboardFacturasIdRoute = DashboardFacturasIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => DashboardFacturasRoute,
} as any)
const DashboardEquipaChannelIdRoute =
  DashboardEquipaChannelIdRouteImport.update({
    id: '/$channelId',
    path: '/$channelId',
    getParentRoute: () => DashboardEquipaRoute,
  } as any)
const DashboardDocumentosNovoRoute = DashboardDocumentosNovoRouteImport.update({
  id: '/novo',
  path: '/novo',
  getParentRoute: () => DashboardDocumentosRoute,
} as any)
const DashboardAssistenteThreadIdRoute =
  DashboardAssistenteThreadIdRouteImport.update({
    id: '/$threadId',
    path: '/$threadId',
    getParentRoute: () => DashboardAssistenteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/empresas': typeof EmpresasRoute
  '/login': typeof LoginRoute
  '/registo': typeof RegistoRoute
  '/api/chat': typeof ApiChatRoute
  '/dashboard/assistente': typeof DashboardAssistenteRouteWithChildren
  '/dashboard/clientes': typeof DashboardClientesRoute
  '/dashboard/cotacoes': typeof DashboardCotacoesRoute
  '/dashboard/definicoes': typeof DashboardDefinicoesRoute
  '/dashboard/design': typeof DashboardDesignRoute
  '/dashboard/documentos': typeof DashboardDocumentosRouteWithChildren
  '/dashboard/equipa': typeof DashboardEquipaRouteWithChildren
  '/dashboard/facturacao': typeof DashboardFacturacaoRoute
  '/dashboard/facturas': typeof DashboardFacturasRouteWithChildren
  '/dashboard/notificacoes': typeof DashboardNotificacoesRoute
  '/dashboard/perfil': typeof DashboardPerfilRoute
  '/dashboard/produtos': typeof DashboardProdutosRoute
  '/dashboard/recibos': typeof DashboardRecibosRoute
  '/dashboard/servicos': typeof DashboardServicosRoute
  '/dashboard/whatsapp': typeof DashboardWhatsappRoute
  '/verificar/$code': typeof VerificarCodeRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/assistente/$threadId': typeof DashboardAssistenteThreadIdRoute
  '/dashboard/documentos/novo': typeof DashboardDocumentosNovoRoute
  '/dashboard/equipa/$channelId': typeof DashboardEquipaChannelIdRoute
  '/dashboard/facturas/$id': typeof DashboardFacturasIdRoute
  '/dashboard/facturas/nova': typeof DashboardFacturasNovaRoute
  '/facturas/$id/imprimir': typeof FacturasIdImprimirRoute
  '/dashboard/assistente/': typeof DashboardAssistenteIndexRoute
  '/dashboard/documentos/': typeof DashboardDocumentosIndexRoute
  '/dashboard/equipa/': typeof DashboardEquipaIndexRoute
  '/dashboard/facturas/': typeof DashboardFacturasIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/empresas': typeof EmpresasRoute
  '/login': typeof LoginRoute
  '/registo': typeof RegistoRoute
  '/api/chat': typeof ApiChatRoute
  '/dashboard/clientes': typeof DashboardClientesRoute
  '/dashboard/cotacoes': typeof DashboardCotacoesRoute
  '/dashboard/definicoes': typeof DashboardDefinicoesRoute
  '/dashboard/design': typeof DashboardDesignRoute
  '/dashboard/facturacao': typeof DashboardFacturacaoRoute
  '/dashboard/notificacoes': typeof DashboardNotificacoesRoute
  '/dashboard/perfil': typeof DashboardPerfilRoute
  '/dashboard/produtos': typeof DashboardProdutosRoute
  '/dashboard/recibos': typeof DashboardRecibosRoute
  '/dashboard/servicos': typeof DashboardServicosRoute
  '/dashboard/whatsapp': typeof DashboardWhatsappRoute
  '/verificar/$code': typeof VerificarCodeRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/assistente/$threadId': typeof DashboardAssistenteThreadIdRoute
  '/dashboard/documentos/novo': typeof DashboardDocumentosNovoRoute
  '/dashboard/equipa/$channelId': typeof DashboardEquipaChannelIdRoute
  '/dashboard/facturas/$id': typeof DashboardFacturasIdRoute
  '/dashboard/facturas/nova': typeof DashboardFacturasNovaRoute
  '/facturas/$id/imprimir': typeof FacturasIdImprimirRoute
  '/dashboard/assistente': typeof DashboardAssistenteIndexRoute
  '/dashboard/documentos': typeof DashboardDocumentosIndexRoute
  '/dashboard/equipa': typeof DashboardEquipaIndexRoute
  '/dashboard/facturas': typeof DashboardFacturasIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/empresas': typeof EmpresasRoute
  '/login': typeof LoginRoute
  '/registo': typeof RegistoRoute
  '/api/chat': typeof ApiChatRoute
  '/dashboard/assistente': typeof DashboardAssistenteRouteWithChildren
  '/dashboard/clientes': typeof DashboardClientesRoute
  '/dashboard/cotacoes': typeof DashboardCotacoesRoute
  '/dashboard/definicoes': typeof DashboardDefinicoesRoute
  '/dashboard/design': typeof DashboardDesignRoute
  '/dashboard/documentos': typeof DashboardDocumentosRouteWithChildren
  '/dashboard/equipa': typeof DashboardEquipaRouteWithChildren
  '/dashboard/facturacao': typeof DashboardFacturacaoRoute
  '/dashboard/facturas': typeof DashboardFacturasRouteWithChildren
  '/dashboard/notificacoes': typeof DashboardNotificacoesRoute
  '/dashboard/perfil': typeof DashboardPerfilRoute
  '/dashboard/produtos': typeof DashboardProdutosRoute
  '/dashboard/recibos': typeof DashboardRecibosRoute
  '/dashboard/servicos': typeof DashboardServicosRoute
  '/dashboard/whatsapp': typeof DashboardWhatsappRoute
  '/verificar/$code': typeof VerificarCodeRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/assistente/$threadId': typeof DashboardAssistenteThreadIdRoute
  '/dashboard/documentos/novo': typeof DashboardDocumentosNovoRoute
  '/dashboard/equipa/$channelId': typeof DashboardEquipaChannelIdRoute
  '/dashboard/facturas/$id': typeof DashboardFacturasIdRoute
  '/dashboard/facturas/nova': typeof DashboardFacturasNovaRoute
  '/facturas/$id/imprimir': typeof FacturasIdImprimirRoute
  '/dashboard/assistente/': typeof DashboardAssistenteIndexRoute
  '/dashboard/documentos/': typeof DashboardDocumentosIndexRoute
  '/dashboard/equipa/': typeof DashboardEquipaIndexRoute
  '/dashboard/facturas/': typeof DashboardFacturasIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/dashboard'
    | '/empresas'
    | '/login'
    | '/registo'
    | '/api/chat'
    | '/dashboard/assistente'
    | '/dashboard/clientes'
    | '/dashboard/cotacoes'
    | '/dashboard/definicoes'
    | '/dashboard/design'
    | '/dashboard/documentos'
    | '/dashboard/equipa'
    | '/dashboard/facturacao'
    | '/dashboard/facturas'
    | '/dashboard/notificacoes'
    | '/dashboard/perfil'
    | '/dashboard/produtos'
    | '/dashboard/recibos'
    | '/dashboard/servicos'
    | '/dashboard/whatsapp'
    | '/verificar/$code'
    | '/dashboard/'
    | '/dashboard/assistente/$threadId'
    | '/dashboard/documentos/novo'
    | '/dashboard/equipa/$channelId'
    | '/dashboard/facturas/$id'
    | '/dashboard/facturas/nova'
    | '/facturas/$id/imprimir'
    | '/dashboard/assistente/'
    | '/dashboard/documentos/'
    | '/dashboard/equipa/'
    | '/dashboard/facturas/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/empresas'
    | '/login'
    | '/registo'
    | '/api/chat'
    | '/dashboard/clientes'
    | '/dashboard/cotacoes'
    | '/dashboard/definicoes'
    | '/dashboard/design'
    | '/dashboard/facturacao'
    | '/dashboard/notificacoes'
    | '/dashboard/perfil'
    | '/dashboard/produtos'
    | '/dashboard/recibos'
    | '/dashboard/servicos'
    | '/dashboard/whatsapp'
    | '/verificar/$code'
    | '/dashboard'
    | '/dashboard/assistente/$threadId'
    | '/dashboard/documentos/novo'
    | '/dashboard/equipa/$channelId'
    | '/dashboard/facturas/$id'
    | '/dashboard/facturas/nova'
    | '/facturas/$id/imprimir'
    | '/dashboard/assistente'
    | '/dashboard/documentos'
    | '/dashboard/equipa'
    | '/dashboard/facturas'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/dashboard'
    | '/empresas'
    | '/login'
    | '/registo'
    | '/api/chat'
    | '/dashboard/assistente'
    | '/dashboard/clientes'
    | '/dashboard/cotacoes'
    | '/dashboard/definicoes'
    | '/dashboard/design'
    | '/dashboard/documentos'
    | '/dashboard/equipa'
    | '/dashboard/facturacao'
    | '/dashboard/facturas'
    | '/dashboard/notificacoes'
    | '/dashboard/perfil'
    | '/dashboard/produtos'
    | '/dashboard/recibos'
    | '/dashboard/servicos'
    | '/dashboard/whatsapp'
    | '/verificar/$code'
    | '/dashboard/'
    | '/dashboard/assistente/$threadId'
    | '/dashboard/documentos/novo'
    | '/dashboard/equipa/$channelId'
    | '/dashboard/facturas/$id'
    | '/dashboard/facturas/nova'
    | '/facturas/$id/imprimir'
    | '/dashboard/assistente/'
    | '/dashboard/documentos/'
    | '/dashboard/equipa/'
    | '/dashboard/facturas/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  EmpresasRoute: typeof EmpresasRoute
  LoginRoute: typeof LoginRoute
  RegistoRoute: typeof RegistoRoute
  ApiChatRoute: typeof ApiChatRoute
  VerificarCodeRoute: typeof VerificarCodeRoute
  FacturasIdImprimirRoute: typeof FacturasIdImprimirRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/registo': {
      id: '/registo'
      path: '/registo'
      fullPath: '/registo'
      preLoaderRoute: typeof RegistoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/empresas': {
      id: '/empresas'
      path: '/empresas'
      fullPath: '/empresas'
      preLoaderRoute: typeof EmpresasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/verificar/$code': {
      id: '/verificar/$code'
      path: '/verificar/$code'
      fullPath: '/verificar/$code'
      preLoaderRoute: typeof VerificarCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/whatsapp': {
      id: '/dashboard/whatsapp'
      path: '/whatsapp'
      fullPath: '/dashboard/whatsapp'
      preLoaderRoute: typeof DashboardWhatsappRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/servicos': {
      id: '/dashboard/servicos'
      path: '/servicos'
      fullPath: '/dashboard/servicos'
      preLoaderRoute: typeof DashboardServicosRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/recibos': {
      id: '/dashboard/recibos'
      path: '/recibos'
      fullPath: '/dashboard/recibos'
      preLoaderRoute: typeof DashboardRecibosRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/produtos': {
      id: '/dashboard/produtos'
      path: '/produtos'
      fullPath: '/dashboard/produtos'
      preLoaderRoute: typeof DashboardProdutosRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/perfil': {
      id: '/dashboard/perfil'
      path: '/perfil'
      fullPath: '/dashboard/perfil'
      preLoaderRoute: typeof DashboardPerfilRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/notificacoes': {
      id: '/dashboard/notificacoes'
      path: '/notificacoes'
      fullPath: '/dashboard/notificacoes'
      preLoaderRoute: typeof DashboardNotificacoesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/facturas': {
      id: '/dashboard/facturas'
      path: '/facturas'
      fullPath: '/dashboard/facturas'
      preLoaderRoute: typeof DashboardFacturasRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/facturacao': {
      id: '/dashboard/facturacao'
      path: '/facturacao'
      fullPath: '/dashboard/facturacao'
      preLoaderRoute: typeof DashboardFacturacaoRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/equipa': {
      id: '/dashboard/equipa'
      path: '/equipa'
      fullPath: '/dashboard/equipa'
      preLoaderRoute: typeof DashboardEquipaRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/documentos': {
      id: '/dashboard/documentos'
      path: '/documentos'
      fullPath: '/dashboard/documentos'
      preLoaderRoute: typeof DashboardDocumentosRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/design': {
      id: '/dashboard/design'
      path: '/design'
      fullPath: '/dashboard/design'
      preLoaderRoute: typeof DashboardDesignRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/definicoes': {
      id: '/dashboard/definicoes'
      path: '/definicoes'
      fullPath: '/dashboard/definicoes'
      preLoaderRoute: typeof DashboardDefinicoesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/cotacoes': {
      id: '/dashboard/cotacoes'
      path: '/cotacoes'
      fullPath: '/dashboard/cotacoes'
      preLoaderRoute: typeof DashboardCotacoesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/clientes': {
      id: '/dashboard/clientes'
      path: '/clientes'
      fullPath: '/dashboard/clientes'
      preLoaderRoute: typeof DashboardClientesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/assistente': {
      id: '/dashboard/assistente'
      path: '/assistente'
      fullPath: '/dashboard/assistente'
      preLoaderRoute: typeof DashboardAssistenteRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/facturas/': {
      id: '/dashboard/facturas/'
      path: '/'
      fullPath: '/dashboard/facturas/'
      preLoaderRoute: typeof DashboardFacturasIndexRouteImport
      parentRoute: typeof DashboardFacturasRoute
    }
    '/dashboard/equipa/': {
      id: '/dashboard/equipa/'
      path: '/'
      fullPath: '/dashboard/equipa/'
      preLoaderRoute: typeof DashboardEquipaIndexRouteImport
      parentRoute: typeof DashboardEquipaRoute
    }
    '/dashboard/documentos/': {
      id: '/dashboard/documentos/'
      path: '/'
      fullPath: '/dashboard/documentos/'
      preLoaderRoute: typeof DashboardDocumentosIndexRouteImport
      parentRoute: typeof DashboardDocumentosRoute
    }
    '/dashboard/assistente/': {
      id: '/dashboard/assistente/'
      path: '/'
      fullPath: '/dashboard/assistente/'
      preLoaderRoute: typeof DashboardAssistenteIndexRouteImport
      parentRoute: typeof DashboardAssistenteRoute
    }
    '/facturas/$id/imprimir': {
      id: '/facturas/$id/imprimir'
      path: '/facturas/$id/imprimir'
      fullPath: '/facturas/$id/imprimir'
      preLoaderRoute: typeof FacturasIdImprimirRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/facturas/nova': {
      id: '/dashboard/facturas/nova'
      path: '/nova'
      fullPath: '/dashboard/facturas/nova'
      preLoaderRoute: typeof DashboardFacturasNovaRouteImport
      parentRoute: typeof DashboardFacturasRoute
    }
    '/dashboard/facturas/$id': {
      id: '/dashboard/facturas/$id'
      path: '/$id'
      fullPath: '/dashboard/facturas/$id'
      preLoaderRoute: typeof DashboardFacturasIdRouteImport
      parentRoute: typeof DashboardFacturasRoute
    }
    '/dashboard/equipa/$channelId': {
      id: '/dashboard/equipa/$channelId'
      path: '/$channelId'
      fullPath: '/dashboard/equipa/$channelId'
      preLoaderRoute: typeof DashboardEquipaChannelIdRouteImport
      parentRoute: typeof DashboardEquipaRoute
    }
    '/dashboard/documentos/novo': {
      id: '/dashboard/documentos/novo'
      path: '/novo'
      fullPath: '/dashboard/documentos/novo'
      preLoaderRoute: typeof DashboardDocumentosNovoRouteImport
      parentRoute: typeof DashboardDocumentosRoute
    }
    '/dashboard/assistente/$threadId': {
      id: '/dashboard/assistente/$threadId'
      path: '/$threadId'
      fullPath: '/dashboard/assistente/$threadId'
      preLoaderRoute: typeof DashboardAssistenteThreadIdRouteImport
      parentRoute: typeof DashboardAssistenteRoute
    }
  }
}

interface DashboardAssistenteRouteChildren {
  DashboardAssistenteThreadIdRoute: typeof DashboardAssistenteThreadIdRoute
  DashboardAssistenteIndexRoute: typeof DashboardAssistenteIndexRoute
}

const DashboardAssistenteRouteChildren: DashboardAssistenteRouteChildren = {
  DashboardAssistenteThreadIdRoute: DashboardAssistenteThreadIdRoute,
  DashboardAssistenteIndexRoute: DashboardAssistenteIndexRoute,
}

const DashboardAssistenteRouteWithChildren =
  DashboardAssistenteRoute._addFileChildren(DashboardAssistenteRouteChildren)

interface DashboardDocumentosRouteChildren {
  DashboardDocumentosNovoRoute: typeof DashboardDocumentosNovoRoute
  DashboardDocumentosIndexRoute: typeof DashboardDocumentosIndexRoute
}

const DashboardDocumentosRouteChildren: DashboardDocumentosRouteChildren = {
  DashboardDocumentosNovoRoute: DashboardDocumentosNovoRoute,
  DashboardDocumentosIndexRoute: DashboardDocumentosIndexRoute,
}

const DashboardDocumentosRouteWithChildren =
  DashboardDocumentosRoute._addFileChildren(DashboardDocumentosRouteChildren)

interface DashboardEquipaRouteChildren {
  DashboardEquipaChannelIdRoute: typeof DashboardEquipaChannelIdRoute
  DashboardEquipaIndexRoute: typeof DashboardEquipaIndexRoute
}

const DashboardEquipaRouteChildren: DashboardEquipaRouteChildren = {
  DashboardEquipaChannelIdRoute: DashboardEquipaChannelIdRoute,
  DashboardEquipaIndexRoute: DashboardEquipaIndexRoute,
}

const DashboardEquipaRouteWithChildren = DashboardEquipaRoute._addFileChildren(
  DashboardEquipaRouteChildren,
)

interface DashboardFacturasRouteChildren {
  DashboardFacturasIdRoute: typeof DashboardFacturasIdRoute
  DashboardFacturasNovaRoute: typeof DashboardFacturasNovaRoute
  DashboardFacturasIndexRoute: typeof DashboardFacturasIndexRoute
}

const DashboardFacturasRouteChildren: DashboardFacturasRouteChildren = {
  DashboardFacturasIdRoute: DashboardFacturasIdRoute,
  DashboardFacturasNovaRoute: DashboardFacturasNovaRoute,
  DashboardFacturasIndexRoute: DashboardFacturasIndexRoute,
}

const DashboardFacturasRouteWithChildren =
  DashboardFacturasRoute._addFileChildren(DashboardFacturasRouteChildren)

interface DashboardRouteChildren {
  DashboardAssistenteRoute: typeof DashboardAssistenteRouteWithChildren
  DashboardClientesRoute: typeof DashboardClientesRoute
  DashboardCotacoesRoute: typeof DashboardCotacoesRoute
  DashboardDefinicoesRoute: typeof DashboardDefinicoesRoute
  DashboardDesignRoute: typeof DashboardDesignRoute
  DashboardDocumentosRoute: typeof DashboardDocumentosRouteWithChildren
  DashboardEquipaRoute: typeof DashboardEquipaRouteWithChildren
  DashboardFacturacaoRoute: typeof DashboardFacturacaoRoute
  DashboardFacturasRoute: typeof DashboardFacturasRouteWithChildren
  DashboardNotificacoesRoute: typeof DashboardNotificacoesRoute
  DashboardPerfilRoute: typeof DashboardPerfilRoute
  DashboardProdutosRoute: typeof DashboardProdutosRoute
  DashboardRecibosRoute: typeof DashboardRecibosRoute
  DashboardServicosRoute: typeof DashboardServicosRoute
  DashboardWhatsappRoute: typeof DashboardWhatsappRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAssistenteRoute: DashboardAssistenteRouteWithChildren,
  DashboardClientesRoute: DashboardClientesRoute,
  DashboardCotacoesRoute: DashboardCotacoesRoute,
  DashboardDefinicoesRoute: DashboardDefinicoesRoute,
  DashboardDesignRoute: DashboardDesignRoute,
  DashboardDocumentosRoute: DashboardDocumentosRouteWithChildren,
  DashboardEquipaRoute: DashboardEquipaRouteWithChildren,
  DashboardFacturacaoRoute: DashboardFacturacaoRoute,
  DashboardFacturasRoute: DashboardFacturasRouteWithChildren,
  DashboardNotificacoesRoute: DashboardNotificacoesRoute,
  DashboardPerfilRoute: DashboardPerfilRoute,
  DashboardProdutosRoute: DashboardProdutosRoute,
  DashboardRecibosRoute: DashboardRecibosRoute,
  DashboardServicosRoute: DashboardServicosRoute,
  DashboardWhatsappRoute: DashboardWhatsappRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRoute,
  DashboardRoute: DashboardRouteWithChildren,
  EmpresasRoute: EmpresasRoute,
  LoginRoute: LoginRoute,
  RegistoRoute: RegistoRoute,
  ApiChatRoute: ApiChatRoute,
  VerificarCodeRoute: VerificarCodeRoute,
  FacturasIdImprimirRoute: FacturasIdImprimirRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
